# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libvirt-dev dbus
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v7
      with:
        version: v2.1.2
    - name: Build
      run: make build
    - name: Test
      run: make test
    - name: Upload Go Binary
      uses: actions/upload-artifact@v4
      with:
        name: libvirt_keepawake_test_binaries
        path: /tmp/test_binaries
